infinispan.client.hotrod.server_list = 127.0.0.1:11222
infinispan.client.hotrod.auth_username = admin
infinispan.client.hotrod.auth_password = admin
infinispan.client.hotrod.auth_realm=default

infinispan.client.hotrod.cache.concurrent-sum.transaction.transaction_manager_lookup = org.infinispan.client.hotrod.transaction.lookup.GenericTransactionManagerLookup
infinispan.client.hotrod.cache.concurrent-sum.transaction.transaction_mode = NON_XA
infinispan.client.hotrod.transaction.timeout = 60000